#!/bin/bash

# Test if they have specified the amount of cores to use, if not just pull them from proc
if [ -z "$1" ]; then
	cores=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | tail -1)
	cores=$(expr $cores + 1)
else
	cores=$1
fi


echo
echo "Using $cores cores to compile with -j $(expr $cores + 1)"
echo
echo

rm -rf executables

echo "Building the server executable"
go build -o executables/server server/main.go

echo "Building the hijacked version executable"
cd hijacked_stockfish/src/
./compile $(expr $cores + 1)
mv hijacked_stockfish.exe ../../executables/hijacked_stockfish.exe
mv hijacked_stockfish ../../executables/hijacked_stockfish

echo "Building the official version executable"
cd ../../stockfish/src/
./compile $(expr $cores + 1)
mv stockfish.exe ../../executables/stockfish.exe
mv stockfish ../../executables/stockfish

echo
echo
echo "*****"
echo "Done compiling both releases and the server."
echo "There is now a folder at the root named 'executables' where they are all stored."
echo "*****"
echo
echo